#!/bin/bash

# Version 1.0 by Rosanne Vetro - August 2013
# Script for running MapReduce app. to find unmapped reads that may correspond to translocation sites

# Script parameters 
SRCJAR=bincat.jar
MANIFEST=manifest.txt

javac -cp *.java

jar cvfm $SRCJAR $MANIFEST *.class


exit 0  


