#!/bin/bash

#Map-Reduce Parameters
mrJar=./mr.jar
echo "$mrJar"
mr_exec=mr

module load hadoop
echo "Mapping and reducing..."
# Set environment variables
#export HADOOP_INSTALL=~/programs/hadoop-1.2.1/
#export PATH=$PATH:${HADOOP_INSTALL}bin:${HADOOP_INSTALL}sbin
#export PATH=$PATH:/usr/lib/jdk1.7.0_25/bin
#MR_HADOOPJAR=~/programs/hadoop-1.2.1/hadoop-core-1.2.1.jar
MR_MANIFEST=./manifest.txt
echo "$MR_MANIFEST"
# Compile mr and create executable jar
echo "Compiling mr source code.."
javac -source 1.6 -classpath hadoop-core-1.2.1.jar ./*.java
#echo "javac -classpath $MR_HADOOPJAR ~/TILSH/mr/src/*.java"
echo "Creating mr jar.."
jar cvfm $mrJar $MR_MANIFEST ./*.class
echo "jar cvfm $mrJar $MR_MANIFEST ~/TILSH/mr/src/*.class"
export HADOOP_CLASSPATH=$mrJar
echo "export HADOOP_CLASSPATH=$mrJar"
#hadoop $mr_exec $sketchsortjPPOutput 
echo "hadoop $mr_exec $sketchsortjPPOutput"
echo "Map-Reduce complete."

exit 0 
